spring.application.name=vechile


spring.datasource.url=jdbc:mysql://localhost:3306/vechiles
spring.datasource.username=root
spring.datasource.password=612721104077Ra

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=9090

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true